// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tyuiu.Courses.Programming.Infrastructure.Persistence;

#nullable disable

namespace Tyuiu.Courses.Programming.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260508095526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CheckpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseSprintId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseSprintId")
                        .IsUnique();

                    b.ToTable("CheckpointEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("GroupId");

                    b.ToTable("CourseEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseParticipantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isModerator")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseParticipantEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseSprintEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int?>("IndexNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<int>("SprintId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("SprintId");

                    b.ToTable("CourseSprintEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseThemeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseSprintId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IndexNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ThemeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseSprintId");

                    b.HasIndex("ThemeId");

                    b.ToTable("CourseThemeEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.DisciplineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.FileDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileDataEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.GroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.QuestionAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionAnswerEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IgnoreCase")
                        .HasColumnType("boolean");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<int?>("ThemeTestId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ThemeTestId");

                    b.ToTable("QuestionEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.SprintEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int?>("IndexNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.ToTable("SprintEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoCheckingTasks")
                        .HasColumnType("boolean");

                    b.Property<int>("IndexNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Introduction")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SprintId")
                        .HasColumnType("integer");

                    b.Property<string>("Theory")
                        .HasColumnType("text");

                    b.Property<string>("VideoURL")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.ToTable("ThemeEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FileDataId")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("ThemeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileDataId");

                    b.HasIndex("ThemeId");

                    b.ToTable("ThemeFileEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeTaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThemeId")
                        .HasColumnType("integer");

                    b.Property<int>("Variant")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("ThemeTaskEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeTestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("PassingScore")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionsCount")
                        .HasColumnType("integer");

                    b.Property<bool>("SavedByUser")
                        .HasColumnType("boolean");

                    b.Property<int>("ThemeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId")
                        .IsUnique();

                    b.ToTable("ThemeTestEntity");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CheckpointEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseSprintEntity", "CourseSprint")
                        .WithOne("Checkpoint")
                        .HasForeignKey("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CheckpointEntity", "CourseSprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSprint");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.DisciplineEntity", "Discipline")
                        .WithMany("Courses")
                        .HasForeignKey("DisciplineId");

                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.Navigation("Discipline");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseParticipantEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseEntity", "Course")
                        .WithMany("Participants")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseSprintEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseEntity", "Course")
                        .WithMany("CourseSprints")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.SprintEntity", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseThemeEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseSprintEntity", "CourseSprint")
                        .WithMany("Themes")
                        .HasForeignKey("CourseSprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeEntity", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSprint");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.DisciplineEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.QuestionAnswerEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.QuestionEntity", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.QuestionEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeTestEntity", "ThemeTest")
                        .WithMany("Questions")
                        .HasForeignKey("ThemeTestId");

                    b.Navigation("ThemeTest");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.SprintEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.DisciplineEntity", "Discipline")
                        .WithMany("Sprints")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.SprintEntity", "Sprint")
                        .WithMany("Themes")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeFileEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.FileDataEntity", "FileData")
                        .WithMany()
                        .HasForeignKey("FileDataId");

                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeEntity", "Theme")
                        .WithMany("Files")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileData");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeTaskEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeEntity", "Theme")
                        .WithMany("Tasks")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeTestEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeEntity", "Theme")
                        .WithOne("Test")
                        .HasForeignKey("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeTestEntity", "ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.UserEntity", b =>
                {
                    b.HasOne("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.GroupEntity", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseEntity", b =>
                {
                    b.Navigation("CourseSprints");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.CourseSprintEntity", b =>
                {
                    b.Navigation("Checkpoint")
                        .IsRequired();

                    b.Navigation("Themes");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.DisciplineEntity", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.GroupEntity", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.QuestionEntity", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.SprintEntity", b =>
                {
                    b.Navigation("Themes");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeEntity", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Tasks");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Tyuiu.Courses.Programming.Infrastructure.Persistence.Entitites.ThemeTestEntity", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
